platform :ios, '10.0'
use_frameworks!
workspace 'Autoload-Models.xcworkspace'

def appPods
end

def sharedPods
end

target 'Autoload-Models' do
    appPods
    sharedPods
    
    target 'Autoload-ModelsTests' do
        inherit! :search_paths
        # Pods for testing
    end
end

target 'Autoload-ModelsCore' do
    project 'Autoload-ModelsCore/Autoload-ModelsCore.xcodeproj'
    sharedPods
    
    target 'Autoload-ModelsCoreTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
